### PR TITLE
Add ability for noecho override

### PR DESCRIPTION
**Pull request by lethrez**
*Issue #19*

*Description of changes:*
Have loved using this helper for custom resources, although a big of a shame it's missing the NoEcho.
this would provide basic functionality to override NoEcho such as:
`helper.NoEcho = True`
I'm happy to add in some tests and update docs/provide an example. I'm just gaining initial opinions on the approach.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by lethrez** [comment]
@jaymccon are you still moderating this project? would be nice to have this functionality.

**Comment by ddaubi** [comment]
This is a must for secure deployment.

**Comment by tjbrockmeyer** [comment]
@jaymccon This is a good change. Can this get pulled in? It's been since May 2020

**Comment by zdot** [comment]
Would be great to get this merged.

**Comment by zdot** [comment]
@jaymccon Thank you! Appreciate your work on this project.

**Comment by ddaubi** [comment]
Thank you!

**Pull request merged**
