### PR TITLE
Allow waiting for CW logs to be configurable

### PR DESCRIPTION
**Pull request by carpnick**
*Issue #, if available:*
#3 

*Description of changes:*
Doesn't change . the behavior just changes the ability for end users to modify it.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

I am willing to create a Unit Test if you think this looks good and I can move forward.

Let me know.

### CODE REVIEW

**Comment by carpnick** [comment]
This is killing our productivity due to not having this option, @jaymccon , can I get an update on this?

**Comment by jaymccon** [comment]
@carpnick `2.0.5` has been pushed to pypi. Apologies for the latency on getting to this one.

**Comment by carpnick** [comment]
Thanks.  Looks like the pushed 2.0.5 still has the old code in it...

```
    def __init__(self, json_logging=False, log_level='DEBUG', boto_level='ERROR', polling_interval=2):
```

**Comment by carpnick** [comment]
@jaymccon FYI on your release it had old code released.  I validated downloading it directly from pypi.org.  I think you will need to spin another one.

**Pull request merged**
